# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\willi\OneDrive\Desktop\VSC\GitHub\Little_Market

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\willi\OneDrive\Desktop\VSC\GitHub\Little_Market

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\willi\OneDrive\Desktop\VSC\GitHub\Little_Market\CMakeFiles C:\Users\willi\OneDrive\Desktop\VSC\GitHub\Little_Market\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\willi\OneDrive\Desktop\VSC\GitHub\Little_Market\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named polysim_core

# Build rule for target.
polysim_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 polysim_core
.PHONY : polysim_core

# fast build rule for target.
polysim_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\polysim_core.dir\build.make CMakeFiles/polysim_core.dir/build
.PHONY : polysim_core/fast

#=============================================================================
# Target rules for targets named polysim

# Build rule for target.
polysim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 polysim
.PHONY : polysim

# fast build rule for target.
polysim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\polysim.dir\build.make CMakeFiles/polysim.dir/build
.PHONY : polysim/fast

#=============================================================================
# Target rules for targets named test_orderbook

# Build rule for target.
test_orderbook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_orderbook
.PHONY : test_orderbook

# fast build rule for target.
test_orderbook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_orderbook.dir\build.make CMakeFiles/test_orderbook.dir/build
.PHONY : test_orderbook/fast

src/bindings/main.obj: src/bindings/main.cpp.obj
.PHONY : src/bindings/main.obj

# target to build an object file
src/bindings/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\polysim.dir\build.make CMakeFiles/polysim.dir/src/bindings/main.cpp.obj
.PHONY : src/bindings/main.cpp.obj

src/bindings/main.i: src/bindings/main.cpp.i
.PHONY : src/bindings/main.i

# target to preprocess a source file
src/bindings/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\polysim.dir\build.make CMakeFiles/polysim.dir/src/bindings/main.cpp.i
.PHONY : src/bindings/main.cpp.i

src/bindings/main.s: src/bindings/main.cpp.s
.PHONY : src/bindings/main.s

# target to generate assembly for a file
src/bindings/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\polysim.dir\build.make CMakeFiles/polysim.dir/src/bindings/main.cpp.s
.PHONY : src/bindings/main.cpp.s

src/core/OrderBook.obj: src/core/OrderBook.cpp.obj
.PHONY : src/core/OrderBook.obj

# target to build an object file
src/core/OrderBook.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\polysim_core.dir\build.make CMakeFiles/polysim_core.dir/src/core/OrderBook.cpp.obj
.PHONY : src/core/OrderBook.cpp.obj

src/core/OrderBook.i: src/core/OrderBook.cpp.i
.PHONY : src/core/OrderBook.i

# target to preprocess a source file
src/core/OrderBook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\polysim_core.dir\build.make CMakeFiles/polysim_core.dir/src/core/OrderBook.cpp.i
.PHONY : src/core/OrderBook.cpp.i

src/core/OrderBook.s: src/core/OrderBook.cpp.s
.PHONY : src/core/OrderBook.s

# target to generate assembly for a file
src/core/OrderBook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\polysim_core.dir\build.make CMakeFiles/polysim_core.dir/src/core/OrderBook.cpp.s
.PHONY : src/core/OrderBook.cpp.s

src/core/test_orderbook.obj: src/core/test_orderbook.cpp.obj
.PHONY : src/core/test_orderbook.obj

# target to build an object file
src/core/test_orderbook.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_orderbook.dir\build.make CMakeFiles/test_orderbook.dir/src/core/test_orderbook.cpp.obj
.PHONY : src/core/test_orderbook.cpp.obj

src/core/test_orderbook.i: src/core/test_orderbook.cpp.i
.PHONY : src/core/test_orderbook.i

# target to preprocess a source file
src/core/test_orderbook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_orderbook.dir\build.make CMakeFiles/test_orderbook.dir/src/core/test_orderbook.cpp.i
.PHONY : src/core/test_orderbook.cpp.i

src/core/test_orderbook.s: src/core/test_orderbook.cpp.s
.PHONY : src/core/test_orderbook.s

# target to generate assembly for a file
src/core/test_orderbook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_orderbook.dir\build.make CMakeFiles/test_orderbook.dir/src/core/test_orderbook.cpp.s
.PHONY : src/core/test_orderbook.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... polysim
	@echo ... polysim_core
	@echo ... test_orderbook
	@echo ... src/bindings/main.obj
	@echo ... src/bindings/main.i
	@echo ... src/bindings/main.s
	@echo ... src/core/OrderBook.obj
	@echo ... src/core/OrderBook.i
	@echo ... src/core/OrderBook.s
	@echo ... src/core/test_orderbook.obj
	@echo ... src/core/test_orderbook.i
	@echo ... src/core/test_orderbook.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

